import mensCasualShirtImage from "./menscasualshirt.jpg"

const productsData = [
  {
    id: 1,
    name: "Wireless Headphones",
    category: "electronics",
    price: 99.99,
    originalPrice: 129.99,
    rating: 4,
    reviews: 125,
    image: "https://images-cdn.ubuy.ae/666e7a4d958aaa681e00b132-wireless-gaming-headsets-for-ps5-ps4.jpg",
    onSale: true,
    trending: true,
    description: "Premium wireless headphones with noise cancellation."
  },
  {
    id: 2,
    name: "Men's Casual Shirt",
    category: "men",
    price: 29.99,
    originalPrice: 39.99,
    rating: 5,
    reviews: 84,
    image: mensCasualShirtImage,
    isTopRated: true,
    onSale: true,
    trending: false,
    description: "Comfortable cotton shirt perfect for casual outings"
  },
   {id: 1,
    name: "Women's Jacket",
    category: "women",
    price: 298.59,
    originalPrice: 551.89,
    rating: 3,
    reviews: 420,
    image: "https://assets.ajio.com/medias/sys_master/root/20240710/jdY8/668dd3e86f60443f31c8c86a/-473Wx593H-700179150-brown-MODEL.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 2,
    name: "Kids' Toy",
    category: "kids",
    price: 163.75,
    originalPrice: 538.92,
    rating: 5,
    reviews: 181,
    image: "https://example.com/images/product_2.jpg",
    onSale: false,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 3,
    name: "Kids' Backpack",
    category: "kids",
    price: 367.19,
    originalPrice: 791.17,
    rating: 3,
    reviews: 421,
    image: "https://example.com/images/product_3.jpg",
    onSale: false,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 4,
    name: "I pad ",
    category: "electronics",
    price: 414.05,
    originalPrice: 533.47,
    rating: 4,
    reviews: 306,
    image: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/ipad-card-40-ipad-202410_FMT_WHH?wid=508&hei=472&fmt=p-jpg&qlt=95&.v=SFZodklRUStGeVJpUE9iYTA5SFFYay9QT3EzOEVhTmwyMUJSTjlXV3hGdGZMQnBkTWowcTVzai9uUEgzVDdYM3NtS0NkZnlUKzBRdlpRai9zMDR0cS9TN0NVaEVIU09sK0c2RHUvMlFZREoxWnZFQ2ozaVJXS3R0eUNrSXRjUEo",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 5,
    name: "Gaming Mouse",
    category: "electronics",
    price: 498.02,
    originalPrice: 541.21,
    rating: 5,
    reviews: 97,
    image: "https://example.com/images/product_5.jpg",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 6,
    name: "Kids' Shirt",
    category: "kids",
    price: 141.09,
    originalPrice: 827.46,
    rating: 1,
    reviews: 239,
    image: "https://example.com/images/product_6.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 7,
    name: "Women's Skirt",
    category: "women",
    price: 324.18,
    originalPrice: 682.92,
    rating: 5,
    isTopRated: true,
    reviews: 170,
    image: "https://example.com/images/product_7.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 8,
    name: "Smartphone",
    category: "electronics",
    price: 283.77,
    originalPrice: 566.25,
    rating: 3,
    reviews: 324,
    image: "https://example.com/images/product_8.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 9,
    name: "Kids' Puzzle",
    category: "kids",
    price: 329.74,
    originalPrice: 837.85,
    rating: 1,
    reviews: 322,
    image: "https://example.com/images/product_9.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 10,
    name: "Women's Dress",
    category: "women",
    price: 95.53,
    originalPrice: 631.94,
    rating: 3,
    reviews: 331,
    image: "https://example.com/images/product_10.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 11,
    name: "Wireless Headphones",
    category: "electronics",
    price: 381.3,
    originalPrice: 612.93,
    rating: 1,
    reviews: 473,
    isTopRated: true,
    image: "https://example.com/images/product_11.jpg",
    onSale: true,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 12,
    name: "Bluetooth Speaker",
    category: "electronics",
    price: 392.93,
    originalPrice: 770.42,
    rating: 5,
    reviews: 78,
    image: "https://example.com/images/product_12.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 13,
    name: "Women's Top",
    category: "women",
    price: 130.92,
    originalPrice: 917.79,
    rating: 3,
    reviews: 161,
    image: "https://example.com/images/product_13.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 14,
    name: "Women's Skirt",
    category: "women",
    price: 422.1,
    originalPrice: 650.26,
    rating: 5,
    reviews: 492,
    image: "https://example.com/images/product_14.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 15,
    name: "Women's Dress",
    category: "women",
    price: 203.97,
    originalPrice: 569.04,
    rating: 5,
    reviews: 94,
    image: "https://example.com/images/product_15.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 16,
    name: "4K Monitor",
    category: "electronics",
    price: 219.55,
    originalPrice: 523.33,
    rating: 2,
    reviews: 378,
    image: "https://example.com/images/product_16.jpg",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 17,
    name: "Men's Jacket",
    category: "men",
    price: 327.76,
    originalPrice: 671.71,
    rating: 4,
    reviews: 46,
    image: "https://example.com/images/product_17.jpg",
    onSale: false,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 18,
    name: "Men's Hoodie",
    category: "men",
    price: 294.62,
    originalPrice: 620.6,
    rating: 3,
    reviews: 379,
    image: "https://example.com/images/product_18.jpg",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 19,
    name: "Gaming Mouse",
    category: "electronics",
    price: 38.72,
    originalPrice: 633.8,
    isTopRated: true,
    rating: 3,
    reviews: 418,
    image: "https://example.com/images/product_19.jpg",
    onSale: false,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 20,
    name: "Women's Skirt",
    category: "women",
    price: 151.08,
    originalPrice: 723.05,
    rating: 1,
    reviews: 483,
    image: "https://example.com/images/product_20.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 21,
    name: "Kids' Backpack",
    category: "kids",
    price: 27.65,
    originalPrice: 636.11,
    isTopRated: true,
    rating: 2,
    reviews: 353,
    image: "https://example.com/images/product_21.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 22,
    name: "Kids' Shoes",
    category: "kids",
    price: 216.81,
    originalPrice: 875.61,
    isTopRated: true,
    rating: 5,
    reviews: 245,
    image: "https://example.com/images/product_22.jpg",
    onSale: false,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 23,
    name: "Men's Jacket",
    category: "men",
    price: 407.44,
    originalPrice: 624.81,
    rating: 3,
    reviews: 497,
    image: "https://example.com/images/product_23.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 24,
    name: "Bluetooth Speaker",
    category: "electronics",
    price: 293.08,
    originalPrice: 676.25,
    rating: 3,
    reviews: 348,
    image: "https://example.com/images/product_24.jpg",
    onSale: false,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 25,
    name: "Men's Casual Shirt",
    category: "men",
    price: 98.09,
    originalPrice: 720.81,
    rating: 2,
    reviews: 331,
    image: "https://cdn.shopify.com/s/files/1/0012/7339/7332/files/17_Vertical_Striped_Shirts_You_Should_Definitely_Own_Right_Now_2048x2048.jpg?v=1673224456",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 26,
    name: "Kids' Shoes",
    category: "kids",
    price: 417.19,
    originalPrice: 803.55,
    rating: 5,
    reviews: 355,
    image: "https://example.com/images/product_26.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 27,
    name: "Men's Jacket",
    category: "men",
    price: 46.74,
    originalPrice: 749.57,
    isTopRated: true,
    rating: 1,
    reviews: 275,
    image: "https://example.com/images/product_27.jpg",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 28,
    name: "Women's Skirt",
    category: "women",
    price: 496.88,
    originalPrice: 861.67,
    rating: 1,
    reviews: 232,
    image: "https://example.com/images/product_28.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 29,
    name: "Men's Jeans",
    category: "men",
    price: 192.52,
    originalPrice: 857.24,
    rating: 2,
    reviews: 199,
    image: "https://example.com/images/product_29.jpg",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 30,
    name: "Gaming Mouse",
    category: "electronics",
    price: 317.3,
    originalPrice: 508.93,
    rating: 5,
    reviews: 162,
    image: "https://example.com/images/product_30.jpg",
    onSale: false,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 31,
    name: "Women's Watch",
    category: "women",
    price: 80.98,
    originalPrice: 667.43,
    rating: 5,
    reviews: 144,
    image: "https://example.com/images/product_31.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 32,
    name: "Smartphone",
    category: "electronics",
    price: 449.37,
    originalPrice: 607.71,
    rating: 1,
    reviews: 103,
    image: "https://example.com/images/product_32.jpg",
    onSale: true,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 33,
    name: "Women's Skirt",
    category: "women",
    price: 173.4,
    originalPrice: 851.31,
    rating: 1,
    reviews: 310,
    image: "https://example.com/images/product_33.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 34,
    name: "Smartphone",
    category: "electronics",
    price: 132.02,
    originalPrice: 826.25,
    rating: 2,
    reviews: 356,
    image: "https://example.com/images/product_34.jpg",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 35,
    name: "Men's Jacket",
    category: "men",
    price: 232.49,
    originalPrice: 591.28,
    rating: 5,
    reviews: 59,
    image: "https://example.com/images/product_35.jpg",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 36,
    name: "Women's Skirt",
    category: "women",
    price: 238.98,
    originalPrice: 611.73,
    rating: 3,
    reviews: 427,
    image: "https://example.com/images/product_36.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 37,
    name: "Wireless Headphones",
    category: "electronics",
    price: 309.93,
    originalPrice: 972.65,
    rating: 1,
    reviews: 346,
    image: "https://example.com/images/product_37.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 38,
    name: "Men's Casual Shirt",
    category: "men",
    price: 320.78,
    originalPrice: 796.29,
    rating: 5,
    reviews: 42,
    image: "https://i.pinimg.com/564x/c5/7d/a9/c57da95e3e69c0f18bb23e3e2378938a.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 39,
    name: "Women's Dress",
    category: "women",
    price: 273.17,
    originalPrice: 990.66,
    rating: 2,
    reviews: 234,
    image: "https://example.com/images/product_39.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 40,
    name: "Women's Skirt",
    category: "women",
    price: 303.37,
    originalPrice: 787.2,
    rating: 4,
    reviews: 16,
    image: "https://example.com/images/product_40.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 41,
    name: "Women's Blouse",
    category: "women",
    price: 452.56,
    originalPrice: 539.08,
    rating: 5,
    reviews: 439,
    image: "https://example.com/images/product_41.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 42,
    name: "4K Monitor",
    category: "electronics",
    price: 257.82,
    originalPrice: 515.53,
    rating: 4,
    reviews: 367,
    image: "https://example.com/images/product_42.jpg",
    onSale: false,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 43,
    name: "Bluetooth Speaker",
    category: "electronics",
    price: 299.26,
    originalPrice: 530.03,
    rating: 4,
    reviews: 46,
    image: "https://example.com/images/product_43.jpg",
    onSale: true,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 44,
    name: "Kids' Toy",
    category: "kids",
    price: 311.84,
    originalPrice: 738.06,
    rating: 1,
    reviews: 251,
    image: "https://example.com/images/product_44.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 45,
    name: "Women's Watch",
    category: "women",
    price: 465.35,
    originalPrice: 532.17,
    rating: 3,
    reviews: 167,
    image: "https://example.com/images/product_45.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 46,
    name: "Women's Top",
    category: "women",
    price: 196.47,
    originalPrice: 535.3,
    rating: 5,
    reviews: 15,
    image: "https://example.com/images/product_46.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 47,
    name: "Women's Top",
    category: "women",
    price: 27.48,
    originalPrice: 926.45,
    rating: 3,
    reviews: 461,
    image: "https://example.com/images/product_47.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 48,
    name: "Kids' Puzzle",
    category: "kids",
    price: 107.43,
    originalPrice: 667.69,
    rating: 5,
    reviews: 106,
    image: "https://example.com/images/product_48.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 49,
    name: "Kids' Shoes",
    category: "kids",
    price: 114.16,
    originalPrice: 992.25,
    rating: 1,
    reviews: 138,
    image: "https://example.com/images/product_49.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 50,
    name: "Men's Watch",
    category: "men",
    price: 402.85,
    originalPrice: 851.08,
    rating: 1,
    reviews: 195,
    image: "https://example.com/images/product_50.jpg",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 51,
    name: "Kids' Shirt",
    category: "kids",
    price: 458.37,
    originalPrice: 582.87,
    rating: 4,
    reviews: 287,
    image: "https://assets.ajio.com/medias/sys_master/root/20240621/Istq/6674abde1d763220fae1314f/-473Wx593H-700109912-black-MODEL.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 52,
    name: "Wireless Headphones",
    category: "electronics",
    price: 468.48,
    originalPrice: 929.08,
    rating: 3,
    reviews: 221,
    image: "https://example.com/images/product_52.jpg",
    onSale: true,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 53,
    name: "Women's Watch",
    category: "women",
    price: 410.89,
    originalPrice: 831.24,
    rating: 1,
    reviews: 252,
    image: "https://example.com/images/product_53.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 54,
    name: "Men's Shirt",
    category: "men",
    price: 142.56,
    originalPrice: 784.23,
    rating: 3,
    reviews: 94,
    image: "https://i.pinimg.com/736x/02/31/c5/0231c5cea761bba7fe3463b63da84b52.jpg",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 55,
    name: "Women's Top",
    category: "women",
    price: 498.99,
    originalPrice: 580.91,
    rating: 4,
    reviews: 237,
    image: "https://example.com/images/product_55.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 56,
    name: "Women's Watch",
    category: "women",
    price: 357.34,
    originalPrice: 644.46,
    rating: 2,
    reviews: 315,
    image: "https://example.com/images/product_56.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 57,
    name: "Men's Jeans",
    category: "men",
    price: 412.06,
    originalPrice: 949.13,
    rating: 5,
    reviews: 242,
    image: "https://example.com/images/product_57.jpg",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 58,
    name: "Men's Jacket",
    category: "men",
    price: 147.4,
    originalPrice: 819.2,
    rating: 1,
    reviews: 399,
    image: "https://example.com/images/product_58.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 59,
    name: "Women's Dress",
    category: "women",
    price: 200.53,
    originalPrice: 875.33,
    rating: 3,
    reviews: 20,
    image: "https://example.com/images/product_59.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 60,
    name: "Women's Dress",
    category: "women",
    price: 270.55,
    originalPrice: 846.03,
    rating: 5,
    reviews: 175,
    image: "https://example.com/images/product_60.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 61,
    name: "4K Monitor",
    category: "electronics",
    price: 342.1,
    originalPrice: 731.41,
    rating: 1,
    reviews: 495,
    image: "https://example.com/images/product_61.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 62,
    name: "Kids' Shoes",
    category: "kids",
    price: 283.96,
    originalPrice: 770.04,
    rating: 4,
    reviews: 13,
    image: "https://example.com/images/product_62.jpg",
    onSale: false,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 63,
    name: "Men's Jeans",
    category: "men",
    price: 71.26,
    originalPrice: 639.92,
    rating: 2,
    reviews: 176,
    image: "https://example.com/images/product_63.jpg",
    onSale: false,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 64,
    name: "Wireless Headphones",
    category: "electronics",
    price: 325.47,
    originalPrice: 977.75,
    rating: 3,
    reviews: 499,
    image: "https://example.com/images/product_64.jpg",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 65,
    name: "Kids' Backpack",
    category: "kids",
    price: 211.35,
    originalPrice: 937.7,
    rating: 4,
    reviews: 143,
    image: "https://example.com/images/product_65.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 66,
    name: "Men's Shirt",
    category: "men",
    price: 119.72,
    originalPrice: 668.38,
    rating: 3,
    reviews: 331,
    image: "https://images.meesho.com/images/products/291468100/phex6_512.webp",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 67,
    name: "Kids' Backpack",
    category: "kids",
    price: 321.21,
    originalPrice: 548.69,
    rating: 5,
    reviews: 243,
    image: "https://example.com/images/product_67.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 68,
    name: "Women's Watch",
    category: "women",
    price: 445.16,
    originalPrice: 927.31,
    rating: 3,
    reviews: 325,
    image: "https://example.com/images/product_68.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 69,
    name: "Women's Top",
    category: "women",
    price: 282.23,
    originalPrice: 619.63,
    rating: 4,
    reviews: 38,
    image: "https://example.com/images/product_69.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 70,
    name: "Bluetooth Speaker",
    category: "electronics",
    price: 140.24,
    originalPrice: 664.06,
    rating: 1,
    reviews: 365,
    image: "https://example.com/images/product_70.jpg",
    onSale: false,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 71,
    name: "Women's Top",
    category: "women",
    price: 103.2,
    originalPrice: 710.82,
    rating: 1,
    reviews: 475,
    image: "https://example.com/images/product_71.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 72,
    name: "Men's Shirt",
    category: "men",
    price: 394.52,
    originalPrice: 983.33,
    rating: 3,
    reviews: 117,
    image: "https://i.pinimg.com/736x/12/2e/34/122e34cbfc9db204583acf3886802127.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 73,
    name: "Kids' Toy",
    category: "kids",
    price: 42.6,
    originalPrice: 863.41,
    rating: 3,
    reviews: 279,
    image: "https://example.com/images/product_73.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 74,
    name: "Bluetooth Speaker",
    category: "electronics",
    price: 434.17,
    originalPrice: 525.25,
    rating: 4,
    reviews: 143,
    image: "https://example.com/images/product_74.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 75,
    name: "Smartphone",
    category: "electronics",
    price: 106.9,
    originalPrice: 964.31,
    rating: 3,
    reviews: 353,
    image: "https://example.com/images/product_75.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 76,
    name: "Men's Jacket",
    category: "men",
    price: 431.9,
    originalPrice: 889.3,
    rating: 3,
    reviews: 479,
    image: "https://images-cdn.ubuy.co.in/65d59896d74c7014fa177219-men-coats-casual-solid-turndown-winter.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 77,
    name: "Men's Jacket",
    category: "men",
    price: 383.85,
    originalPrice: 894.17,
    rating: 4,
    reviews: 227,
    image: "https://example.com/images/product_77.jpg",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 78,
    name: "Women's Top",
    category: "women",
    price: 491.45,
    originalPrice: 964.29,
    rating: 2,
    reviews: 104,
    image: "https://example.com/images/product_78.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 79,
    name: "Kids' Shirt",
    category: "kids",
    price: 246.61,
    originalPrice: 841.52,
    rating: 3,
    reviews: 51,
    image: "https://example.com/images/product_79.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 80,
    name: "Kids' Toy",
    category: "kids",
    price: 398.7,
    originalPrice: 845.09,
    rating: 5,
    reviews: 17,
    image: "https://example.com/images/product_80.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 81,
    name: "Smartphone",
    category: "electronics",
    price: 298.98,
    originalPrice: 532.25,
    rating: 5,
    reviews: 249,
    image: "https://example.com/images/product_81.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 82,
    name: "4K Monitor",
    category: "electronics",
    price: 121.3,
    originalPrice: 756.21,
    rating: 1,
    reviews: 256,
    image: "https://example.com/images/product_82.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 83,
    name: "Women's Skirt",
    category: "women",
    price: 196.29,
    originalPrice: 862.01,
    rating: 3,
    reviews: 81,
    image: "https://example.com/images/product_83.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 84,
    name: "Kids' Puzzle",
    category: "kids",
    price: 180.25,
    originalPrice: 874.73,
    rating: 1,
    reviews: 433,
    image: "https://example.com/images/product_84.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 85,
    name: "Kids' Backpack",
    category: "kids",
    price: 347.12,
    originalPrice: 831.5,
    rating: 5,
    reviews: 300,
    image: "https://example.com/images/product_85.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 86,
    name: "Women's Skirt",
    category: "women",
    price: 301.73,
    originalPrice: 622.31,
    rating: 5,
    reviews: 134,
    image: "https://example.com/images/product_86.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 87,
    name: "Women's Blouse",
    category: "women",
    price: 267.05,
    originalPrice: 644.5,
    rating: 1,
    reviews: 272,
    image: "https://example.com/images/product_87.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 88,
    name: "Men's Jacket",
    category: "men",
    price: 496.37,
    originalPrice: 744.38,
    rating: 4,
    reviews: 67,
    image: "https://example.com/images/product_88.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 89,
    name: "Men's Watch",
    category: "men",
    price: 392.82,
    originalPrice: 694.67,
    rating: 3,
    reviews: 122,
    image: "https://example.com/images/product_89.jpg",
    onSale: false,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 90,
    name: "Wireless Headphones",
    category: "electronics",
    price: 450.35,
    originalPrice: 776.09,
    rating: 4,
    reviews: 320,
    image: "https://example.com/images/product_90.jpg",
    onSale: false,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 91,
    name: "Women's Top",
    category: "women",
    price: 308.47,
    originalPrice: 634.07,
    rating: 2,
    reviews: 164,
    image: "https://example.com/images/product_91.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 92,
    name: "Kids' Puzzle",
    category: "kids",
    price: 456.18,
    originalPrice: 755.83,
    rating: 1,
    reviews: 95,
    image: "https://example.com/images/product_92.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 93,
    name: "Women's Top",
    category: "women",
    price: 304.15,
    originalPrice: 559.8,
    rating: 5,
    reviews: 422,
    image: "https://example.com/images/product_93.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 94,
    name: "Kids' Shoes",
    category: "kids",
    price: 150.17,
    originalPrice: 879.36,
    rating: 5,
    reviews: 213,
    image: "https://example.com/images/product_94.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 95,
    name: "Kids' Shoes",
    category: "kids",
    price: 71.63,
    originalPrice: 565.32,
    rating: 5,
    reviews: 99,
    image: "https://example.com/images/product_95.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 96,
    name: "Men's T-Shirt",
    category: "men",
    price: 273.85,
    originalPrice: 673.36,
    rating: 5,
    reviews: 171,
    image: "https://www.beyoung.in/blog/wp-content/uploads/2020/02/full-sleeve-T-shirts-2-853x1024.jpg",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 97,
    name: "Women's Top",
    category: "women",
    price: 140.92,
    originalPrice: 592.74,
    rating: 2,
    reviews: 131,
    image: "https://example.com/images/product_97.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 98,
    name: "Kids' Puzzle",
    category: "kids",
    price: 119.01,
    originalPrice: 573.97,
    rating: 5,
    reviews: 63,
    image: "https://example.com/images/product_98.jpg",
    onSale: false,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 99,
    name: "Women's Skirt",
    category: "women",
    price: 273.46,
    originalPrice: 905.9,
    rating: 2,
    reviews: 31,
    image: "https://example.com/images/product_99.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 100,
    name: "Men's Casual Shirt",
    category: "men",
    price: 48.21,
    originalPrice: 770.59,
    rating: 2,
    reviews: 196,
    image: "https://i.pinimg.com/736x/cc/4e/84/cc4e8496ac5e3e23c94d99b4bc9c1a1f.jpg",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 101,
    name: "Bluetooth Speaker",
    category: "electronics",
    price: 28.68,
    originalPrice: 966.88,
    rating: 1,
    reviews: 422,
    image: "https://example.com/images/product_101.jpg",
    onSale: true,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 102,
    name: "Women's Dress",
    category: "women",
    price: 25.62,
    originalPrice: 905.58,
    rating: 4,
    reviews: 174,
    image: "https://example.com/images/product_102.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 103,
    name: "Men's Jeans",
    category: "men",
    price: 112.64,
    originalPrice: 981.51,
    rating: 5,
    reviews: 124,
    image: "https://example.com/images/product_103.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 104,
    name: "4K Monitor",
    category: "electronics",
    price: 317.18,
    originalPrice: 646.69,
    rating: 5,
    reviews: 265,
    image: "https://example.com/images/product_104.jpg",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 105,
    name: "Wireless Headphones",
    category: "electronics",
    price: 283.29,
    originalPrice: 950.21,
    rating: 4,
    reviews: 310,
    image: "https://example.com/images/product_105.jpg",
    onSale: false,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 106,
    name: "Kids' Shirt",
    category: "kids",
    price: 276.1,
    originalPrice: 866.71,
    rating: 2,
    reviews: 114,
    image: "https://example.com/images/product_106.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 107,
    name: "Wireless Headphones",
    category: "electronics",
    price: 357.62,
    originalPrice: 580.11,
    rating: 5,
    reviews: 392,
    image: "https://example.com/images/product_107.jpg",
    onSale: false,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 108,
    name: "Women's Skirt",
    category: "women",
    price: 126.45,
    originalPrice: 542.02,
    rating: 3,
    reviews: 129,
    image: "https://example.com/images/product_108.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 109,
    name: "4K Monitor",
    category: "electronics",
    price: 449.51,
    originalPrice: 702.6,
    rating: 2,
    reviews: 141,
    image: "https://example.com/images/product_109.jpg",
    onSale: false,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 110,
    name: "Women's Watch",
    category: "women",
    price: 475.55,
    originalPrice: 614.13,
    rating: 4,
    reviews: 262,
    image: "https://example.com/images/product_110.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 111,
    name: "Men's Jacket",
    category: "men",
    price: 270.27,
    originalPrice: 862.6,
    rating: 1,
    reviews: 272,
    image: "https://example.com/images/product_111.jpg",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 112,
    name: "Men's Casual Shirt",
    category: "men",
    price: 54.06,
    originalPrice: 982.47,
    rating: 1,
    reviews: 411,
    image: "https://i.pinimg.com/736x/02/45/f3/0245f330826907f5fb749f47534543ab.jpg",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 113,
    name: "Women's Blouse",
    category: "women",
    price: 381.05,
    originalPrice: 639.29,
    rating: 2,
    reviews: 417,
    image: "https://example.com/images/product_113.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 114,
    name: "Bluetooth Speaker",
    category: "electronics",
    price: 212.89,
    originalPrice: 632.95,
    rating: 2,
    reviews: 107,
    image: "https://example.com/images/product_114.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 115,
    name: "Women's Skirt",
    category: "women",
    price: 304.8,
    originalPrice: 851.31,
    rating: 4,
    reviews: 285,
    image: "https://example.com/images/product_115.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 116,
    name: "Women's Dress",
    category: "women",
    price: 321.05,
    originalPrice: 519.51,
    rating: 1,
    reviews: 267,
    image: "https://example.com/images/product_116.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 117,
    name: "Men's Watch",
    category: "men",
    price: 383.49,
    originalPrice: 613.4,
    rating: 4,
    reviews: 230,
    image: "https://example.com/images/product_117.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 118,
    name: "Kids' Toy",
    category: "kids",
    price: 36.46,
    originalPrice: 666.34,
    rating: 5,
    reviews: 454,
    image: "https://example.com/images/product_118.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 119,
    name: "Kids' Backpack",
    category: "kids",
    price: 478.16,
    originalPrice: 811.88,
    rating: 3,
    reviews: 70,
    image: "https://example.com/images/product_119.jpg",
    onSale: false,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 120,
    name: "Smartphone",
    category: "electronics",
    price: 103.47,
    originalPrice: 773.69,
    rating: 5,
    reviews: 134,
    image: "https://example.com/images/product_120.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 121,
    name: "Kids' Backpack",
    category: "kids",
    price: 442.18,
    originalPrice: 711.86,
    rating: 4,
    reviews: 161,
    image: "https://example.com/images/product_121.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 122,
    name: "Men's Jacket",
    category: "men",
    price: 91.79,
    originalPrice: 512.56,
    rating: 4,
    reviews: 48,
    image: "https://5.imimg.com/data5/HW/PB/UP/SELLER-75155666/mens-puffer-jacket.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 123,
    name: "Wireless Headphones",
    category: "electronics",
    price: 156.9,
    originalPrice: 540.17,
    rating: 5,
    reviews: 80,
    image: "https://example.com/images/product_123.jpg",
    onSale: false,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 124,
    name: "Kids' Shoes",
    category: "kids",
    price: 319.07,
    originalPrice: 761.65,
    rating: 2,
    reviews: 464,
    image: "https://example.com/images/product_124.jpg",
    onSale: false,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 125,
    name: "Kids' Puzzle",
    category: "kids",
    price: 354.37,
    originalPrice: 636.23,
    rating: 1,
    reviews: 317,
    image: "https://example.com/images/product_125.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 126,
    name: "Men's Jeans",
    category: "men",
    price: 328.3,
    originalPrice: 935.92,
    rating: 2,
    reviews: 412,
    image: "https://example.com/images/product_126.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 127,
    name: "4K Monitor",
    category: "electronics",
    price: 443.13,
    originalPrice: 806.08,
    rating: 2,
    reviews: 146,
    image: "https://example.com/images/product_127.jpg",
    onSale: true,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 128,
    name: "Men's T- Shirt",
    category: "men",
    price: 179.0,
    originalPrice: 876.88,
    rating: 3,
    reviews: 402,
    image: "https://cdn.lookastic.com/looks/crew-neck-t-shirt-chinos-low-top-sneakers-large-76771.jpg",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 129,
    name: "Women's Blouse",
    category: "women",
    price: 255.14,
    originalPrice: 630.41,
    rating: 5,
    reviews: 268,
    image: "https://example.com/images/product_129.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 130,
    name: "Women's Dress",
    category: "women",
    price: 247.64,
    originalPrice: 806.68,
    rating: 1,
    reviews: 298,
    image: "https://example.com/images/product_130.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 131,
    name: "Kids' Backpack",
    category: "kids",
    price: 251.85,
    originalPrice: 646.74,
    rating: 3,
    reviews: 438,
    image: "https://example.com/images/product_131.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 132,
    name: "Kids' Shoes",
    category: "kids",
    price: 99.03,
    originalPrice: 910.57,
    rating: 5,
    reviews: 209,
    image: "https://example.com/images/product_132.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 133,
    name: "Men's Polo Shirt",
    category: "men",
    price: 59.17,
    originalPrice: 701.67,
    rating: 3,
    reviews: 219,
    image: "https://lifestylebyps.com/cdn/shop/articles/rowanrow_20180729113944_1024x1024.png?v=1532852585",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 134,
    name: "Women's Skirt",
    category: "women",
    price: 221.67,
    originalPrice: 773.16,
    rating: 5,
    reviews: 482,
    image: "https://example.com/images/product_134.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 135,
    name: "Women's Top",
    category: "women",
    price: 121.12,
    originalPrice: 963.77,
    rating: 2,
    reviews: 235,
    image: "https://example.com/images/product_135.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 136,
    name: "Kids' Puzzle",
    category: "kids",
    price: 227.5,
    originalPrice: 991.7,
    rating: 4,
    reviews: 425,
    image: "https://example.com/images/product_136.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 137,
    name: "Men's Jacket",
    category: "men",
    price: 159.36,
    originalPrice: 962.74,
    rating: 5,
    reviews: 161,
    image: "https://i.pinimg.com/564x/8a/4f/33/8a4f33a7fda5b736e9e1185e5f5e87d7.jpg",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 138,
    name: "Men's Watch",
    category: "men",
    price: 98.31,
    originalPrice: 679.17,
    rating: 2,
    reviews: 492,
    image: "https://example.com/images/product_138.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 139,
    name: "Men's Jacket",
    category: "men",
    price: 346.38,
    originalPrice: 741.67,
    rating: 2,
    reviews: 381,
    image: "https://down-sg.img.susercontent.com/file/cn-11134207-7r98o-lnb7kso2j53cca",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 140,
    name: "Men's polo Shirt",
    category: "men",
    price: 336.81,
    originalPrice: 690.19,
    rating: 3,
    reviews: 259,
    image: "https://images.fashiontiy.com/products/T10384CE104/color_0.jpg?x-oss-process=image/interlace,1/format,webp",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 141,
    name: "Men's T-Shirt",
    category: "men",
    price: 272.46,
    originalPrice: 579.04,
    rating: 3,
    reviews: 85,
    image: "https://neticapparel.com/cdn/shop/products/t-shirt-mockup-of-a-bearded-man-with-an-arm-tattoo-1025-el_530x@2x.png?v=1615427391",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 142,
    name: "Women's Skirt",
    category: "women",
    price: 225.24,
    originalPrice: 590.82,
    rating: 5,
    reviews: 14,
    image: "https://example.com/images/product_142.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 143,
    name: "Kids' Backpack",
    category: "kids",
    price: 268.79,
    originalPrice: 746.94,
    rating: 3,
    reviews: 293,
    image: "https://example.com/images/product_143.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 144,
    name: "Women's Skirt",
    category: "women",
    price: 333.44,
    originalPrice: 691.0,
    rating: 4,
    reviews: 19,
    image: "https://example.com/images/product_144.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 145,
    name: "Women's Skirt",
    category: "women",
    price: 31.09,
    originalPrice: 933.81,
    rating: 5,
    reviews: 449,
    image: "https://example.com/images/product_145.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 146,
    name: "Men's Casual Shirt",
    category: "men",
    price: 482.86,
    originalPrice: 853.33,
    rating: 1,
    reviews: 90,
    image: "https://example.com/images/product_146.jpg",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 147,
    name: "Kids' Puzzle",
    category: "kids",
    price: 280.93,
    originalPrice: 969.09,
    rating: 3,
    reviews: 478,
    image: "https://example.com/images/product_147.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 148,
    name: "Gaming Mouse",
    category: "electronics",
    price: 328.18,
    originalPrice: 706.48,
    rating: 1,
    reviews: 195,
    image: "https://example.com/images/product_148.jpg",
    onSale: false,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 149,
    name: "Wireless Headphones",
    category: "electronics",
    price: 181.03,
    originalPrice: 721.6,
    rating: 5,
    reviews: 306,
    image: "https://example.com/images/product_149.jpg",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 150,
    name: "Smartphone",
    category: "electronics",
    price: 292.84,
    originalPrice: 512.36,
    rating: 1,
    reviews: 68,
    image: "https://example.com/images/product_150.jpg",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 151,
    name: "Women's Watch",
    category: "women",
    price: 182.89,
    originalPrice: 823.56,
    rating: 2,
    reviews: 118,
    image: "https://example.com/images/product_151.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 152,
    name: "Bluetooth Speaker",
    category: "electronics",
    price: 468.81,
    originalPrice: 675.66,
    rating: 5,
    reviews: 344,
    image: "https://example.com/images/product_152.jpg",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 153,
    name: "Kids' Shoes",
    category: "kids",
    price: 91.72,
    originalPrice: 636.07,
    rating: 5,
    reviews: 460,
    image: "https://example.com/images/product_153.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 154,
    name: "Women's Skirt",
    category: "women",
    price: 452.22,
    originalPrice: 938.71,
    rating: 3,
    reviews: 100,
    image: "https://example.com/images/product_154.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 155,
    name: "4K Monitor",
    category: "electronics",
    price: 413.61,
    originalPrice: 747.56,
    rating: 3,
    reviews: 281,
    image: "https://example.com/images/product_155.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 156,
    name: "Kids' Puzzle",
    category: "kids",
    price: 182.59,
    originalPrice: 700.83,
    rating: 4,
    reviews: 33,
    image: "https://example.com/images/product_156.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 157,
    name: "Men's Casual Shirt",
    category: "men",
    price: 398.37,
    originalPrice: 615.71,
    rating: 4,
    reviews: 128,
    image: "https://example.com/images/product_157.jpg",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 158,
    name: "4K Monitor",
    category: "electronics",
    price: 320.2,
    originalPrice: 694.91,
    rating: 2,
    reviews: 199,
    image: "https://example.com/images/product_158.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 159,
    name: "4K Monitor",
    category: "electronics",
    price: 181.7,
    originalPrice: 525.69,
    rating: 3,
    reviews: 486,
    image: "https://example.com/images/product_159.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 160,
    name: "Men's Jacket",
    category: "men",
    price: 492.01,
    originalPrice: 540.21,
    rating: 3,
    reviews: 400,
    image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/jacket/l/f/p/xl-1-no-mf-cb-jkt-21-black-mia-fashion-original-imah59h5yf9rzvcq.jpeg?q=90&crop=false",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 161,
    name: "Men's Casual Shirt",
    category: "men",
    price: 354.81,
    originalPrice: 963.67,
    rating: 3,
    reviews: 172,
    image: "https://example.com/images/product_161.jpg",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 162,
    name: "Smartphone",
    category: "electronics",
    price: 260.77,
    originalPrice: 704.02,
    rating: 4,
    reviews: 72,
    image: "https://example.com/images/product_162.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 163,
    name: "Wireless Headphones",
    category: "electronics",
    price: 191.62,
    originalPrice: 626.4,
    rating: 3,
    reviews: 251,
    image: "https://example.com/images/product_163.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 164,
    name: "Kids' Shoes",
    category: "kids",
    price: 164.49,
    originalPrice: 876.43,
    rating: 5,
    reviews: 299,
    image: "https://example.com/images/product_164.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 165,
    name: "Kids' Shirt",
    category: "kids",
    price: 336.32,
    originalPrice: 836.3,
    rating: 5,
    reviews: 407,
    image: "https://example.com/images/product_165.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 166,
    name: "Women's Dress",
    category: "women",
    price: 380.07,
    originalPrice: 636.59,
    rating: 5,
    reviews: 304,
    image: "https://example.com/images/product_166.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 167,
    name: "Kids' Puzzle",
    category: "kids",
    price: 280.49,
    originalPrice: 984.72,
    rating: 3,
    reviews: 51,
    image: "https://example.com/images/product_167.jpg",
    onSale: false,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 168,
    name: "Men's Casual Shirt",
    category: "men",
    price: 240.45,
    originalPrice: 536.69,
    rating: 4,
    reviews: 303,
    image: "https://example.com/images/product_168.jpg",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 169,
    name: "Gaming Mouse",
    category: "electronics",
    price: 129.03,
    originalPrice: 594.57,
    rating: 4,
    reviews: 371,
    image: "https://example.com/images/product_169.jpg",
    onSale: true,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 170,
    name: "Men's Watch",
    category: "men",
    price: 250.88,
    originalPrice: 988.7,
    rating: 4,
    reviews: 448,
    image: "https://example.com/images/product_170.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 171,
    name: "Women's Watch",
    category: "women",
    price: 127.15,
    originalPrice: 775.09,
    rating: 2,
    reviews: 431,
    image: "https://example.com/images/product_171.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 172,
    name: "Women's Blouse",
    category: "women",
    price: 35.68,
    originalPrice: 745.69,
    rating: 5,
    reviews: 211,
    image: "https://example.com/images/product_172.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 173,
    name: "Women's Watch",
    category: "women",
    price: 392.61,
    originalPrice: 609.58,
    rating: 5,
    reviews: 29,
    image: "https://example.com/images/product_173.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 174,
    name: "Men's Watch",
    category: "men",
    price: 406.1,
    originalPrice: 556.67,
    rating: 2,
    reviews: 39,
    image: "https://example.com/images/product_174.jpg",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 175,
    name: "Kids' Puzzle",
    category: "kids",
    price: 303.16,
    originalPrice: 980.65,
    rating: 1,
    reviews: 285,
    image: "https://example.com/images/product_175.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 176,
    name: "Women's Top",
    category: "women",
    price: 346.78,
    originalPrice: 752.77,
    rating: 5,
    reviews: 26,
    image: "https://example.com/images/product_176.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 177,
    name: "Kids' Shirt",
    category: "kids",
    price: 91.44,
    originalPrice: 660.33,
    rating: 1,
    reviews: 188,
    image: "https://example.com/images/product_177.jpg",
    onSale: false,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 178,
    name: "Smartphone",
    category: "electronics",
    price: 146.13,
    originalPrice: 741.97,
    rating: 1,
    reviews: 424,
    image: "https://example.com/images/product_178.jpg",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 179,
    name: "Women's Dress",
    category: "women",
    price: 374.34,
    originalPrice: 581.15,
    rating: 4,
    reviews: 19,
    image: "https://example.com/images/product_179.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 180,
    name: "Women's Top",
    category: "women",
    price: 342.02,
    originalPrice: 873.35,
    rating: 2,
    reviews: 472,
    image: "https://example.com/images/product_180.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 181,
    name: "Bluetooth Speaker",
    category: "electronics",
    price: 66.88,
    originalPrice: 835.57,
    rating: 3,
    reviews: 174,
    image: "https://example.com/images/product_181.jpg",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 182,
    name: "Women's Dress",
    category: "women",
    price: 408.21,
    originalPrice: 542.74,
    rating: 3,
    reviews: 330,
    image: "https://example.com/images/product_182.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 183,
    name: "Women's Top",
    category: "women",
    price: 199.02,
    originalPrice: 651.85,
    rating: 2,
    reviews: 307,
    image: "https://example.com/images/product_183.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 184,
    name: "Smartphone",
    category: "electronics",
    price: 169.15,
    originalPrice: 907.54,
    rating: 4,
    reviews: 283,
    image: "https://example.com/images/product_184.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 185,
    name: "Women's Top",
    category: "women",
    price: 370.6,
    originalPrice: 811.4,
    rating: 3,
    reviews: 486,
    image: "https://example.com/images/product_185.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 186,
    name: "Kids' Puzzle",
    category: "kids",
    price: 231.2,
    originalPrice: 566.18,
    rating: 1,
    reviews: 302,
    image: "https://example.com/images/product_186.jpg",
    onSale: false,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 187,
    name: "Kids' Toy",
    category: "kids",
    price: 244.79,
    originalPrice: 928.56,
    rating: 1,
    reviews: 175,
    image: "https://example.com/images/product_187.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 188,
    name: "Kids' Shirt",
    category: "kids",
    price: 169.6,
    originalPrice: 939.87,
    rating: 5,
    reviews: 140,
    image: "https://example.com/images/product_188.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 189,
    name: "Men's Jeans",
    category: "men",
    price: 203.8,
    originalPrice: 955.3,
    rating: 1,
    reviews: 195,
    image: "https://example.com/images/product_189.jpg",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 190,
    name: "Kids' Shirt",
    category: "kids",
    price: 376.82,
    originalPrice: 655.15,
    rating: 2,
    reviews: 78,
    image: "https://example.com/images/product_190.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 191,
    name: "Kids' Shoes",
    category: "kids",
    price: 196.63,
    originalPrice: 960.52,
    rating: 1,
    reviews: 214,
    image: "https://example.com/images/product_191.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 192,
    name: "Men's Casual Shirt",
    category: "men",
    price: 348.38,
    originalPrice: 865.77,
    rating: 5,
    reviews: 266,
    image: "https://example.com/images/product_192.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 193,
    name: "Women's Top",
    category: "women",
    price: 57.35,
    originalPrice: 641.39,
    rating: 3,
    reviews: 185,
    image: "https://example.com/images/product_193.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 194,
    name: "Women's Blouse",
    category: "women",
    price: 486.17,
    originalPrice: 929.91,
    rating: 3,
    reviews: 334,
    image: "https://example.com/images/product_194.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 195,
    name: "Kids' Shoes",
    category: "kids",
    price: 298.7,
    originalPrice: 845.9,
    rating: 5,
    reviews: 387,
    image: "https://example.com/images/product_195.jpg",
    onSale: false,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 196,
    name: "Men's Jacket",
    category: "men",
    price: 457.98,
    originalPrice: 918.12,
    rating: 5,
    reviews: 457,
    image: "https://i5.walmartimages.com/asr/1a9256cc-0ada-4c26-9e78-e7e51b891319.2c82550308180f217517a602ea23a45c.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 197,
    name: "Kids' Toy",
    category: "kids",
    price: 170.69,
    originalPrice: 931.65,
    rating: 3,
    reviews: 370,
    image: "https://example.com/images/product_197.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 198,
    name: "4K Monitor",
    category: "electronics",
    price: 115.8,
    originalPrice: 599.46,
    rating: 4,
    reviews: 399,
    image: "https://example.com/images/product_198.jpg",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 199,
    name: "Kids' Backpack",
    category: "kids",
    price: 449.25,
    originalPrice: 535.92,
    rating: 4,
    reviews: 49,
    image: "https://example.com/images/product_199.jpg",
    onSale: false,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 200,
    name: "Men's Jeans",
    category: "men",
    price: 272.89,
    originalPrice: 672.3,
    rating: 5,
    reviews: 284,
    image: "https://example.com/images/product_200.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 201,
    name: "Gaming Mouse",
    category: "electronics",
    price: 283.0,
    originalPrice: 707.09,
    rating: 2,
    reviews: 77,
    image: "https://example.com/images/product_201.jpg",
    onSale: true,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 202,
    name: "Kids' Toy",
    category: "kids",
    price: 139.63,
    originalPrice: 714.37,
    rating: 2,
    reviews: 368,
    image: "https://example.com/images/product_202.jpg",
    onSale: false,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 203,
    name: "Kids' Puzzle",
    category: "kids",
    price: 273.62,
    originalPrice: 522.59,
    rating: 1,
    reviews: 125,
    image: "https://example.com/images/product_203.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 204,
    name: "Kids' Toy",
    category: "kids",
    price: 462.06,
    originalPrice: 558.11,
    rating: 4,
    reviews: 419,
    image: "https://example.com/images/product_204.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 205,
    name: "Kids' Shoes",
    category: "kids",
    price: 145.63,
    originalPrice: 830.59,
    rating: 3,
    reviews: 61,
    image: "https://example.com/images/product_205.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 206,
    name: "Women's Watch",
    category: "women",
    price: 481.96,
    originalPrice: 941.33,
    rating: 2,
    reviews: 105,
    image: "https://example.com/images/product_206.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 207,
    name: "Kids' Shirt",
    category: "kids",
    price: 192.37,
    originalPrice: 766.04,
    rating: 3,
    reviews: 175,
    image: "https://example.com/images/product_207.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 208,
    name: "Women's Watch",
    category: "women",
    price: 199.94,
    originalPrice: 530.92,
    rating: 3,
    reviews: 333,
    image: "https://example.com/images/product_208.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 209,
    name: "Smartphone",
    category: "electronics",
    price: 308.01,
    originalPrice: 837.49,
    rating: 2,
    reviews: 405,
    image: "https://example.com/images/product_209.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 210,
    name: "Men's Watch",
    category: "men",
    price: 402.96,
    originalPrice: 723.74,
    rating: 1,
    reviews: 489,
    image: "https://example.com/images/product_210.jpg",
    onSale: false,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 211,
    name: "Kids' Puzzle",
    category: "kids",
    price: 240.14,
    originalPrice: 709.72,
    rating: 4,
    reviews: 424,
    image: "https://example.com/images/product_211.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 212,
    name: "Women's Blouse",
    category: "women",
    price: 470.72,
    originalPrice: 979.44,
    rating: 3,
    reviews: 476,
    image: "https://example.com/images/product_212.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 213,
    name: "Men's Casual Shirt",
    category: "men",
    price: 166.35,
    originalPrice: 671.69,
    rating: 2,
    reviews: 423,
    image: "https://i.pinimg.com/736x/51/3c/b6/513cb6cf35729e05ad3675753bb68efc.jpg",
    onSale: false,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 214,
    name: "Women's Skirt",
    category: "women",
    price: 126.98,
    originalPrice: 614.95,
    rating: 5,
    reviews: 408,
    image: "https://example.com/images/product_214.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 215,
    name: "Men's T-Shirt",
    category: "men",
    price: 63.44,
    originalPrice: 818.34,
    rating: 3,
    reviews: 41,
    image: "https://assets.ajio.com/medias/sys_master/root/20230105/KeoQ/63b6fef4f997ddfdbd1715de/-473Wx593H-469431911-grey-MODEL6.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 216,
    name: "Women's Dress",
    category: "women",
    price: 29.01,
    originalPrice: 732.77,
    rating: 5,
    reviews: 72,
    image: "https://example.com/images/product_216.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 217,
    name: "Men's polo T-shrit",
    category: "men",
    price: 225.03,
    originalPrice: 543.55,
    rating: 1,
    reviews: 273,
    image: "https://i5.walmartimages.com/asr/d1a5c80b-5d7f-435c-991f-b9d603e93b63.4c4e029722e1000b8bdaba6395efa2eb.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 218,
    name: "Wireless Headphones",
    category: "electronics",
    price: 199.87,
    originalPrice: 686.12,
    rating: 2,
    reviews: 265,
    image: "https://example.com/images/product_218.jpg",
    onSale: false,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 219,
    name: "Wireless Headphones",
    category: "electronics",
    price: 494.37,
    originalPrice: 611.33,
    rating: 1,
    reviews: 230,
    image: "https://example.com/images/product_219.jpg",
    onSale: true,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 220,
    name: "Women's Blouse",
    category: "women",
    price: 331.08,
    originalPrice: 781.79,
    rating: 5,
    reviews: 260,
    image: "https://example.com/images/product_220.jpg",
    onSale: true,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 221,
    name: "Kids' Shirt",
    category: "kids",
    price: 90.3,
    originalPrice: 843.81,
    rating: 3,
    reviews: 72,
    image: "https://example.com/images/product_221.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 222,
    name: "Gaming Mouse",
    category: "electronics",
    price: 228.52,
    originalPrice: 632.13,
    rating: 3,
    reviews: 377,
    image: "https://example.com/images/product_222.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 223,
    name: "Men's Jeans",
    category: "men",
    price: 360.4,
    originalPrice: 914.02,
    rating: 1,
    reviews: 419,
    image: "https://example.com/images/product_223.jpg",
    onSale: true,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 224,
    name: "Kids' Puzzle",
    category: "kids",
    price: 479.23,
    originalPrice: 755.91,
    rating: 4,
    reviews: 234,
    image: "https://example.com/images/product_224.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 225,
    name: "Men's Casual Shirt",
    category: "men",
    price: 53.92,
    originalPrice: 702.51,
    rating: 4,
    reviews: 17,
    image: "https://images.jdmagicbox.com/quickquotes/images_main/linen-shirt-for-men-2011631000-i7c19opl.jpg",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 226,
    name: "Women's Dress",
    category: "women",
    price: 173.38,
    originalPrice: 675.69,
    rating: 4,
    reviews: 12,
    image: "https://example.com/images/product_226.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 227,
    name: "Women's Skirt",
    category: "women",
    price: 179.55,
    originalPrice: 913.13,
    rating: 5,
    reviews: 277,
    image: "https://example.com/images/product_227.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 228,
    name: "Women's Watch",
    category: "women",
    price: 113.03,
    originalPrice: 978.74,
    rating: 3,
    reviews: 426,
    image: "https://example.com/images/product_228.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 229,
    name: "Men's polo T-shrit",
    category: "men",
    price: 190.2,
    originalPrice: 908.7,
    rating: 4,
    reviews: 420,
    image: "https://img4.dhresource.com/webp/m/0x0/f3/albu/jc/j/06/72899d14-eee4-49e2-b8f6-40732214cb8d.jpg",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 230,
    name: "4K Monitor",
    category: "electronics",
    price: 98.74,
    originalPrice: 900.22,
    rating: 2,
    reviews: 182,
    image: "https://example.com/images/product_230.jpg",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 231,
    name: "Men's Sweatshirt",
    category: "men",
    price: 91.71,
    originalPrice: 974.33,
    rating: 4,
    reviews: 190,
    image: "https://triprindia.com/cdn/shop/files/TGYHNFULSWEAT-PLAINST1601_3783ee97-957d-4f87-8edd-b72d6e98c975_800x.jpg?v=1735826217",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 232,
    name: "Kids' Shoes",
    category: "kids",
    price: 280.64,
    originalPrice: 563.22,
    rating: 1,
    reviews: 105,
    image: "https://example.com/images/product_232.jpg",
    onSale: false,
    trending: true,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 233,
    name: "Women's Watch",
    category: "women",
    price: 181.59,
    originalPrice: 850.88,
    rating: 3,
    reviews: 136,
    image: "https://example.com/images/product_233.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 234,
    name: "Women's Blouse",
    category: "women",
    price: 84.65,
    originalPrice: 759.02,
    rating: 1,
    reviews: 254,
    image: "https://example.com/images/product_234.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 235,
    name: "4K Monitor",
    category: "electronics",
    price: 472.36,
    originalPrice: 809.36,
    rating: 2,
    reviews: 454,
    image: "https://example.com/images/product_235.jpg",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 236,
    name: "Smartphone",
    category: "electronics",
    price: 238.79,
    originalPrice: 988.2,
    rating: 1,
    reviews: 337,
    image: "https://example.com/images/product_236.jpg",
    onSale: false,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 237,
    name: "Men's Sweatshirt",
    category: "men",
    price: 25.69,
    originalPrice: 994.22,
    rating: 2,
    reviews: 135,
    image: "https://m.media-amazon.com/images/I/71F-+tJ8V7L._AC_SX522_.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 238,
    name: "Kids' Puzzle",
    category: "kids",
    price: 92.42,
    originalPrice: 790.52,
    rating: 2,
    reviews: 68,
    image: "https://example.com/images/product_238.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 239,
    name: "Men's Jeans",
    category: "men",
    price: 86.93,
    originalPrice: 901.18,
    rating: 2,
    reviews: 364,
    image: "https://example.com/images/product_239.jpg",
    onSale: true,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 240,
    name: "Kids' Shoes",
    category: "kids",
    price: 462.25,
    originalPrice: 974.22,
    rating: 3,
    reviews: 464,
    image: "https://example.com/images/product_240.jpg",
    onSale: true,
    trending: false,
    description: "Fun and safe for kids of all ages."
  },
  {
     id: 241,
    name: "4K Monitor",
    category: "electronics",
    price: 318.25,
    originalPrice: 866.84,
    rating: 3,
    reviews: 353,
    image: "https://example.com/images/product_241.jpg",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 242,
    name: "Women's Watch",
    category: "women",
    price: 17.79,
    originalPrice: 784.68,
    rating: 4,
    reviews: 215,
    image: "https://example.com/images/product_242.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 243,
    name: "Women's Blouse",
    category: "women",
    price: 95.62,
    originalPrice: 984.31,
    rating: 1,
    reviews: 441,
    image: "https://example.com/images/product_243.jpg",
    onSale: true,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 244,
    name: "Men's Jacket",
    category: "men",
    price: 450.31,
    originalPrice: 681.92,
    rating: 2,
    reviews: 272,
    image: "https://example.com/images/product_244.jpg",
    onSale: false,
    trending: true,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 245,
    name: "Women's Skirt",
    category: "women",
    price: 325.24,
    originalPrice: 622.27,
    rating: 3,
    reviews: 132,
    image: "https://example.com/images/product_245.jpg",
    onSale: false,
    trending: true,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 246,
    name: "Women's Blouse",
    category: "women",
    price: 30.53,
    originalPrice: 573.26,
    rating: 3,
    reviews: 357,
    image: "https://example.com/images/product_246.jpg",
    onSale: false,
    trending: false,
    description: "Elegant and fashionable women's clothing item."
  },
  {
     id: 247,
    name: "Men's Hoodie",
    category: "men",
    price: 448.72,
    originalPrice: 524.8,
    rating: 5,
    reviews: 327,
    image: "https://example.com/images/product_247.jpg",
    onSale: false,
    trending: false,
    description: "Stylish and comfortable men's clothing item."
  },
  {
     id: 248,
    name: "Bluetooth Speaker",
    category: "electronics",
    price: 308.65,
    originalPrice: 910.16,
    rating: 2,
    reviews: 18,
    image: "https://www.boat-lifestyle.com/cdn/shop/files/Stone_SpinXPro_1.png?v=1709717404",
    onSale: false,
    trending: true,
    description: "High-quality electronic gadget with advanced features."
  },
  {
     id: 249,
    name: "Bluetooth Speaker",
    category: "electronics",
    price: 143.02,
    originalPrice: 793.23,
    rating: 4,
    reviews: 263,
    image: "https://www.sony.co.in/image/990c23317d5559ba35b67e564c12a5b3?fmt=png-alpha&wid=660&hei=660",
    onSale: true,
    trending: false,
    description: "High-quality electronic gadget with advanced features."
  },
  {
    id: 250,
    name: "Kids' Shirt",
    category: "kids",
    price: 402.38,
    originalPrice: 965.34,
    rating: 2,
    reviews: 276,
    image:"https://assets.ajio.com/medias/sys_master/root/20240621/Istq/6674abde1d763220fae1314f/-473Wx593H-700109912-black-MODEL.jpg",
    onSale: true,
    trending: true,
    description: "Fun and safe for kids of all ages."
  }
]
  
;

export default productsData;
